app:
  name: gin-scaffold-v2
  env: prod
  port: 80

mysql:
  host: mysql-service
  port: 3306
  user: app
  password: prod_password
  dbname: production
  max_open_conn: 100
  max_idle_conn: 20
  max_lifetime: 3600

redis:
  host: redis-service
  port: 6379max_open_conn: 
  password: ""
  db: 0
  max_idle_conn: 20
  max_lifetime: 3600
