app:
  name: gin-scaffold
  env: dev
  port: 8080

mysql:
  host: localhost
  port: 3306
  user: root
  password: root
  dbname: test
  max_open_conn: 100
  max_idle_conn: 20
  max_lifetime: 3600

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 100
  min_idle_conn: 20

log:
  level: debug
  filename: app.log
